# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iw2NmPFQpEFW-T23wuDWom1WVhAZpMQs
"""

!python3 pl_bolts/models/self_supervised/simsiam/simsiam_module.py --gpus 1 --dataset stl10 --data_dir /data/ --batch_size 32